apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: kube-system
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: www.chenliujin.com 
    http:
      paths:
      - path: /grafana/
        backend:
          serviceName: monitoring-grafana 
          servicePort: 80
  tls:
  - hosts:
    - www.chenliujin.com
    secretName: www.chenliujin.com

