apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
# Can also use LoadBalancer type
  type: NodePort
  ports:
  - name: http
    port: 8080
    nodePort: 30080
    targetPort: 80
    protocol: TCP
  selector:
    app: ingress-nginx
