- hosts: k8s-cluster
  tasks:
    - name: ip_forward
      shell: echo 1 > /proc/sys/net/ipv4/ip_forward

    - name: ip_forward
      lineinfile:
        dest: /etc/sysctl.conf
        regexp: '^net.ipv4.ip_forward'
        line: 'net.ipv4.ip_forward = 1'

    - name: sysctl
      copy:
        src: ./etc/sysctl.d/k8s.conf
        dest: /etc/sysctl.d/

    - name: sysctl
      shell: sysctl --system

    - name: repo
      copy:
        src: ./etc/yum.repos.d/kubernetes.repo
        dest: /etc/yum.repos.d/

    - name: kubeadm
      yum: name=kubeadm state=latest

    - name: kubelet
      shell: systemctl enable kubelet; systemctl start kubelet
