- hosts: k8s-node
  remote_user: root
  tasks:
    - name: k8s image script
      copy: src=./bin/kubeadm-node.sh dest=~/

    - name: k8s image
      shell: bash ~/kubeadm-node.sh

    - name: k8s image script finish
      shell: rm -f ~/kubeadm-node.sh

    - set_fact: cluster_join_script={{ hostvars[groups['k8s-master'][0]]['cluster_join_script'] }}

    - name: kube join
      shell: echo '' | {{ cluster_join_script }}
      when: cluster_join_script is defined
